# -*- coding: utf-8 -*-
"""nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GffaqadAcMTo6jff37UbJl0rLCOCD0ap
"""

import re

def detect_word_pattern(pat, text):
    result = re.findall(pat, text)

    if result:
        print("Word pattern detected:")
        for i in result:
            print(i)
    else:
        print("No word pattern detected")


complex_inputs = [
    (r"\bG\w+", "Hey, great games gather here tonight"),
    (r"\b\d{4}\b", "I was born in the year of 2006"),
    (r"\b[a-zA-Z]{5}\b", "Hello, I am Samsu and this is python"),
    (r"\bjoy\b", "Gaming is a great stress buster")
]

for pat, text in complex_inputs:
    print("Pattern:", pat)
    print("Text:", text)
    detect_word_pattern(pat, text)
    print("-" * 40)